name: 'run'

on:
  schedule:
    - cron: '10 */8 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'setup python'
        uses: actions/setup-python@master
        with: 
          python-version: 3.11
          

      - name: requirements
        run : pip3 install -r requirements.txt

      - name: main
        env:
          cookie_javbus: ${{ secrets.cookie_javbus }}
        run: |
          python3 ../javbus/javbus.py
          
